theme: jekyll-theme-minimal
title: Arne Bechensteen
description: > # this means to ignore newlines until "baseurl:"
  Here I will write about my research interests and keep you updated with new codes and publications.
  
  Do not hesitate to <a href="mailto:arne-henrik.bechensteen@inria.fr">contact me</a> for any questions. 
 
logo: GBilde.png
