theme: jekyll-theme-minimal
title: Welcome to Arne Bechensteen`s home page! 
description: Here I will write about my research interests and keep you updated with new codes and publications.
Address:
Laboratoire d'Informatique, Signaux et Systèmes de Sophia-Antipolis (I3S), 
2000,  Route des lucioles, Les Algorithmes - bât. Euclide B,  bureau 119.
06903,  Sophia Antipolis - France.
e-mail:
arne-henrik.bechensteen@inria.fr


