theme: jekyll-theme-minimal
title: IN WORK!
description: > # this means to ignore newlines until "baseurl:"
  Here I will write about my research interests and keep you updated with new codes and publications.
  
  Do not hesitate to [contact me](mailto:arne-henrik.bechensteen@inria.fr) for any questions. 
