theme: jekyll-theme-minimal
title: In WORK: Welcome to Arne Bechensteen`s home page! 
description: Here I will write about my research interests and keep you updated with new codes and publications. \\e-mail:\\ arne-henrik.bechensteen@inria.fr


